* Vocabulary
** 运维 
网络 EOMS; DevOps; ITIL
** 政府 [zhèng fǔ] 
na. government | 网络 administration; state; the government
** 文化 [wén huà] 
na. culture; civilization; literacy | 网络 Culture; cultural; cultures
** 儿歌 [ér gē] 
na. children's song; nursery rhymes | 网络 Nursery Rhymes; Songs; Children's Song
** extraneous [ɪk'streɪniəs]
adj. 没有直接联系的；无关的 | 网络 外来的；无关系的；外部的 | Synonym adj. irrelevant,unrelated,unconnected,inappropriate,beside the point | Antonym adj. pertinent,essential
** bogus ['bəʊɡəs]
adj. 假的；伪造的 | n. 赝品 | 网络 妈咪也疯狂；假冒的；冒牌 | Synonym adj. false,fake,counterfeit,phony,phoney | Antonym adj. genuine
** atypical [.eɪ'tɪpɪk(ə)l]
adj. 非典型的 | 网络 不规则的；意思是非典型的；不典型 | Synonym adj. different,unusual,uncommon,strange,odd | Antonym adj. typical
** awry [ə'raɪ]
adj. 歪斜的 | adv. 扭曲地 | 网络 扭曲的；走样的；歪曲的 | Synonym adj. crooked,askew,skewed,off beam,out of kilter | Antonym adj. straight,all right
** bail [beɪl]
n. 保释；【法律】保释金；保释人；(篷帐的)半圆形支撑箍托 | v. 担保；舀；从(船中)戽出水；【法律】准许保释 | 网络 保证金；保证人；租约 | Synonym n. bond,financial guarantee,payment,security,surety
** 恢复 [huī fù] 
na. restore; recover; resume; regain | 网络 Recovery; restoration; get over
** 还原 [huán yuán] 
na. restore; reducing; revivification | 网络 Restore; reduction; reduce
** 复原 [fù yuán] 
na. restoration; recovery | 网络 Recovery; Undo; Restore
** finesse [fɪ'nes]
n. 手段；手腕；策略 | v. 用策略对付某事；巧妙地做；派头十足地做 | 网络 技巧；飞牌；偷牌 | Synonym n. skill,flair,grace,elegance,poise | Antonym n. clumsiness,tactlessness
** entangle [ɪn'tæŋɡ(ə)l]
v. 使纠缠；缠住；套住；使卷入 | 网络 使混乱；使陷入；纠缠术 | Synonym v. tangle,snare,ensnare,catch up,enmesh | Antonym v. free
** takeaway ['teɪkə.weɪ]
n. 外卖餐馆；外卖的饭菜；外卖食物 | 网络 外卖店；外卖食品；外带 | Synonym adj. to go,ready-made,precooked,prepared n. takeout,ready meal,carryout,fast food
** unveile 
网络 揭开谜底
** acquaint [ə'kweɪnt]
v. 使熟悉；使了解 | 网络 认识；使认识；相识 | Synonym v. inform,let know,let in on,apprise,familiarize | Antonym v. keep from
** acquainted [ə'kweɪntɪd]
adj. 熟悉；了解；（与某人）相识 | v. “acquaint”的过去分词和过去式 | 网络 知晓的；熟悉的；对某事物熟悉的 | Synonym adj. familiar,conversant,accustomed,used to,au fait
** intersperse [.ɪntə(r)'spɜː(r)s]
v. 散布；散置；点缀 | 网络 分散；埸迭；撒布 | Synonym v. mix together,combine,scatter,spread,sprinkle
** brevity ['brevəti]
n. 简洁；简练；短暂 | 网络 简短；简洁明了；简短明了 | Synonym n. shortness,briefness,quickness,swiftness,transience | Antonym n. length
** gloss [ɡlɒs]
n. 光亮；用以产生光泽的物质；光泽涂料；亮光漆 | v. 在…上作注释（或评注） | 网络 光泽度；光彩；注解 | Synonym v. annotate,interpret,explain,comment on,note n. luster,polish,annotation,commentary,interpretation | Antonym n. misinformation
** whirlwind ['wɜː(r)l.wɪnd]
n. 旋风；旋流；一片忙乱 | adj. 快速的；匆匆忙忙的；旋风似的 | 网络 旋风斩；龙卷风；旋风行动 | Synonym n. tornado,hurricane,cyclone,waterspout,twister adj. rapid,short-lived,tumultuous,brief,swift | Antonym adj. leisurely
** bloat [bləʊt]
n. 〈美〉肿胀病人；(家畜的)气胀病；〈美俚〉醉鬼 | v. 肿胀 | 网络 膨胀；胃气胀；臌胀 | Synonym v. swell,inflate,blow up,expand,distend | Antonym v. contract
** hexadecimal [.heksə'desɪm(ə)l]
adj. 十六进制的 | 网络 十六进位；十六进制数；十六进位制
** gist [dʒɪst]
n. 要点；大意；主旨 | 网络 胃肠道间质瘤；胃肠间质瘤；胃肠道间质肿瘤 | Synonym n. idea,essence,substance,point,meaning
** boilerplate ['bɔɪlə(r).pleɪt]
n. （可供模仿的）样板文件 | 网络 构建样板；创建样板；飞行器的试验样品
** venerable ['ven(ə)rəb(ə)l]
adj. （因年高、显要、智慧等）令人尊重的 | 网络 庄严的；值得尊敬的；可尊敬的 | Synonym adj. respected,august,esteemed,honored,honoured | Antonym adj. disreputable
** viable ['vaɪəb(ə)l]
adj. 可实施的；切实可行的；可生存的；能独立发展的 | 网络 能养活的；能生存的；能活的 | Synonym adj. practicable,feasible,worthwhile,practical,sustainable | Antonym adj. impossible
** maze [meɪz]
n. 迷宫；错综复杂；纵横交错；密如蛛网 | v. 使困惑 | 网络 迷津；迷惑；曲径 | Synonym n. labyrinth,warren,network,web,confusion | Antonym n. order
** grok [ɡrɒk]
v. 通过感觉意会 | 网络 格洛克；神交；格罗克
** conjure ['kʌndʒə(r)]
v. 变戏法；变魔术；使…变戏法般地出现（或消失） | 网络 祈求；恳求；召唤 | Synonym v. raise,summon,call up,invoke,conjure up
** linear ['lɪniə(r)]
adj. 线的；直线的；线状的；（进展）直线式的 | 网络 线性；凌特；线性的 | Synonym adj. lined,line,rectilinear,direct,undeviating
** nutshell ['nʌt.ʃel]
n. 坚果的外壳；极小的容器；窄小的房屋；没有价值的东西 | adj. 扼要的 | 网络 坚果壳；坚果外壳；果壳铃 | Synonym n. husk,casing,shell,outer
** condom ['kɒndɒm]
n. 安全套；（女用）避孕套 | 网络 保险套；阴茎套；男用避孕套
** 避孕套 [bì yùn tào] 
n. condom; contraceptive sheath | 网络 Condoms; French letter; use a condom
** 裤子 [kù zi] [kù zǐ] 
na. trousers; pants | 网络 Pants; Bottoms; Pantaloons
** antonyms ['æntənɪm]
n. 反义词 | 网络 反义字；相反词；反义词风暴
** synonyms ['sɪnənɪm]
n. 同义词；【生】(同物)异名；〈口〉类似物；【生化】同义密码子 | 网络 同义字；数据库中所有同义词；同物异名 | Synonym n. alternative word,substitute,replacement
** apricot [ˈeɪprɪˌkɒt]
n. 杏黄色；【植】杏；【植】杏树；杏色 | 网络 杏子；杏桃；杏仁
** 杏 [xìng]
n. apricot; 【食,植】apricot; a surname | 网络 Prunus armeniaca; Apricots; Armeniaca vulgaris
** Commentary ['kɒmənt(ə)ri]
n. 评论；注释；解释；评注 | 网络 解说词；实况报道；批评 | Synonym n. comment,explanation,observation,note,annotation
** trademark [ˈtreɪdˌmɑː(r)k]
n. 商标；标记；招牌动作；特征 | 网络 注册商标；牌号；商标权 | Synonym n. symbol,logo,emblem,brand,characteristic
** helm [helm]
v. 掌(舵)；掌握；给…戴上头盔 | n. 舵柄；舵轮 | 网络 海姆；驾驶盘；战法之盔
** ivy ['aɪvɪ]
n. 【植】常春藤；长春藤 | 网络 艾薇；许嘉凌；艾维
** generic [dʒə'nerɪk]
adj. 一般的；普通的；通用的；无厂家商标的 | n. 同“a generic drug” | 网络 泛型；类属；属的 | Synonym adj. general,broad,common,basic,nonspecific | Antonym adj. specific
** refine [rɪ'faɪn]
v. 精炼；改进；改善；提纯 | 网络 精制；精练；提炼 | Synonym v. purify,process,treat,filter,distill | Antonym v. contaminate,coarsen
** semicolon
n. 分号 | 网络 分号键；分号读作；分号的用法
** hereby [hɪə(r)'baɪ]
adv. 特此；以此 | 网络 据此；兹；在此
** tutorial [tjuː'tɔːriəl]
n. 教程；（大学导师的）个别辅导时间；辅导材料；使用说明书 | adj. 导师的；私人教师的；辅导的 | 网络 指南；辅导课；个别指导 | Synonym n. class,lesson,seminar,lecture,discussion group
** bonus ['bəʊnəs]
n. 奖金；红利；意外收获 | 网络 额外津贴；花红；奖励 | Synonym n. extra,plus,addition,advantage,windfall
** scratch [skrætʃ]
v. 划伤；挠；取消；刮坏 | n. 划伤；搔痒；刮（或擦、抓）的刺耳声；挠痒 | adj. 仓促拼凑的；无让杆的；无差点的 | 网络 刮伤；刮痕；扒 | Synonym v. itch,rub,grate,abrade,cancel n. cut,scrape,graze,score,nick | Antonym v. keep,continue
** 结婚纪念日
网络 Wedding Anniversary; The Wedding Date; wedding day
** concise [kən'saɪs]
adj. 简明的；简练的；简洁的；简略的 | 网络 简约；精炼；简要的 | Synonym adj. brief,short,to the point,succinct,summarizing | Antonym adj. verbose
** internally [ɪn'tɜːnəli]
adv. 内部的；体内的 | 网络 在内部；内部地；从内部 | Synonym adv. inside,within,on the inside | Antonym adv. outside
** internal [ɪn'tɜː(r)n(ə)l]
n. 内脏；本质 | adj. 内部的；里面的；体内的；（机构）内部的 | 网络 国内的；内在的；内同步 | Synonym adj. interior,inner,inside,core,heart | Antonym adj. external
** aka [.eɪ keɪ 'eɪ]
abbr. 又名；亦称 | 网络 抗角蛋白抗体(Anti-keratin antibody)；宜客；又名(also known as)
** browser ['braʊzə(r)]
n. 浏览器；浏览程序；浏览图书报刊者；逛商店的人 | 网络 网页浏览器；自带浏览器；计算机浏览器服务
** 浏览器 [liú lǎn qì]
n. browser | 网络 Browser; IE; Internet Explorer
** vocabulary [vəʊ'kæbjʊləri]
n. 词汇量；（某一语言的）词汇；（某学科中所使用的）词汇 | 网络 词汇表；字汇；单字 | Synonym n. words,language,terms,expressions,terminology
